import React from 'react';
import { PGConfig, WorkloadType } from '../types';
import { Download, Table as TableIcon, Settings, Shield } from 'lucide-react';
import { motion } from 'motion/react';

interface ConfigResultsProps {
  config: PGConfig;
  currentWorkload: WorkloadType;
}

export const ConfigResults: React.FC<ConfigResultsProps> = ({ config, currentWorkload }) => {
  const [activeTab, setActiveTab] = React.useState<'comparison' | 'export'>('comparison');

  const handleDownloadPG = () => {
    let content = '# PostgreSQL Optimized Configuration\n';
    content += '# Generated by PGConfig Expert\n\n';
    
    Object.entries(config).forEach(([key, value]) => {
      if (key !== 'pgbouncer') {
        content += `${key} = ${value}\n`;
      }
    });

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'postgresql.conf';
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadBouncer = () => {
    if (!config.pgbouncer) return;
    
    let content = '# PgBouncer Configuration\n';
    content += '[databases]\n';
    content += 'non-prod-lt-muthoot = host=xxxxx port=5432 dbname=non-prod-lt-muthoot user=xxxx password=xxxxxxx\n\n';
    content += '[pgbouncer]\n';
    Object.entries(config.pgbouncer).forEach(([key, value]) => {
      content += `${key} = ${value}\n`;
    });

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'pgbouncer.ini';
    a.click();
    URL.revokeObjectURL(url);
  };

  const allPGParams = Object.entries(config)
    .filter(([key]) => key !== 'pgbouncer')
    .map(([key, value]) => ({ name: key, value }));

  return (
    <div className="space-y-6">
      <div className="flex border-b border-slate-200">
        <button
          onClick={() => setActiveTab('comparison')}
          className={`px-6 py-3 text-sm font-bold uppercase tracking-wider transition-colors border-b-2 ${
            activeTab === 'comparison' ? 'border-brand-primary text-brand-primary' : 'border-transparent text-slate-500 hover:text-slate-700'
          }`}
        >
          Configuration Details
        </button>
        <button
          onClick={() => setActiveTab('export')}
          className={`px-6 py-3 text-sm font-bold uppercase tracking-wider transition-colors border-b-2 ${
            activeTab === 'export' ? 'border-brand-primary text-brand-primary' : 'border-transparent text-slate-500 hover:text-slate-700'
          }`}
        >
          Export Config
        </button>
      </div>

      {activeTab === 'comparison' ? (
        <div className="space-y-8">
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="bg-slate-50 border-b border-slate-200">
                  <th className="p-4 text-xs font-bold text-slate-500 uppercase">Parameter</th>
                  <th className={`p-4 text-xs font-bold uppercase bg-brand-primary text-white`}>Recommended Value</th>
                  <th className="p-4 text-xs font-bold text-slate-500 uppercase">Description</th>
                </tr>
              </thead>
              <tbody>
                {allPGParams.map((param) => (
                  <tr key={param.name} className="border-b border-slate-100 hover:bg-slate-50 transition-colors">
                    <td className="p-4 text-sm font-mono text-slate-600">{param.name}</td>
                    <td className={`p-4 text-sm font-bold text-brand-primary bg-brand-primary/5`}>
                      {param.value}
                    </td>
                    <td className="p-4 text-xs text-slate-400 italic">
                      Optimized for {currentWorkload} workload
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {config.pgbouncer && (
            <div className="glass-card p-6 bg-slate-50 border-brand-primary/20">
              <div className="flex items-center gap-2 mb-4">
                <Shield size={18} className="text-brand-primary" />
                <h3 className="font-bold text-slate-800 uppercase text-xs tracking-widest">PgBouncer Settings</h3>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {Object.entries(config.pgbouncer).map(([key, value]) => (
                  <div key={key} className="bg-white p-3 rounded border border-slate-200">
                    <div className="text-[10px] font-bold text-slate-400 uppercase mb-1">{key.replace(/_/g, ' ')}</div>
                    <div className="text-sm font-mono font-bold text-brand-primary">{value}</div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      ) : (
        <div className="space-y-8">
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-bold text-slate-800 uppercase tracking-widest">postgresql.conf</h3>
              <button onClick={handleDownloadPG} className="btn-primary flex items-center gap-2 !py-2 !px-4 !text-[10px]">
                <Download size={14} />
                Download postgresql.conf
              </button>
            </div>
            <pre className="bg-slate-900 text-slate-300 p-6 rounded-lg overflow-x-auto font-mono text-xs leading-relaxed max-h-[300px]">
              {`# PostgreSQL Configuration
# Generated for ${currentWorkload.toUpperCase()} workload

${Object.entries(config)
  .filter(([key]) => key !== 'pgbouncer')
  .map(([key, value]) => `${key.padEnd(30)} = ${value}`)
  .join('\n')}`}
            </pre>
          </div>

          {config.pgbouncer && (
            <div className="space-y-4">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-bold text-slate-800 uppercase tracking-widest">pgbouncer.ini</h3>
                <button onClick={handleDownloadBouncer} className="btn-primary flex items-center gap-2 !py-2 !px-4 !text-[10px]">
                  <Download size={14} />
                  Download pgbouncer.ini
                </button>
              </div>
              <pre className="bg-slate-900 text-slate-300 p-6 rounded-lg overflow-x-auto font-mono text-xs leading-relaxed max-h-[300px]">
                {`[databases]
non-prod-lt-muthoot = host=xxxxx port=5432 dbname=non-prod-lt-muthoot user=xxxx password=xxxxxxx

[pgbouncer]
${Object.entries(config.pgbouncer)
  .map(([key, value]) => `${key.padEnd(30)} = ${value}`)
  .join('\n')}`}
              </pre>
            </div>
          )}
        </div>
      )}
    </div>
  );
};
